server:
  ssl:
    key-store-password: password
    key-store-type: pkcs12
    key-store: classpath:secureapi.jks
    key-password: password
    key-alias: secureapi
  port: 8085

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/secure_database
    username: postgres
    password: L@stochk@9
  flyway:
    url: jdbc:postgresql://localhost:5432/secure_database
    locations: classpath:db/migration
    user: postgres
    password: L@stochk@9

jwt:
  password:
    encoder:
      secret: BLK7RT43odqS13e8aENggaMbb_fAkl-nJL4AEVBX56y
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: proselyte